export const plantData = [
  {
    id: 1,
    name: "Fern",
    category: 1,
    price: 25,
    lightNeeds: "Low Light",
    waterNeeds: "Moderate Water",
    tag: "BestSelling",
    ratings: 4.8,
    sell: 120,
    img: "/assets/plants/p1",
  },
  {
    id: 2,
    name: "Pothos",
    category: 2,
    price: 45,
    lightNeeds: "Low Light",
    waterNeeds: "Moderate Water",
    tag: "NewArrival",
    ratings: 4.9,
    sell: 12,
    img: "/assets/plants/p2",
  },
  {
    id: 3,
    name: "Succulent",
    category: 3,
    price: 30,
    lightNeeds: "Bright Light",
    waterNeeds: "Low Water",
    tag: "BestSelling",
    ratings: 4.7,
    sell: 80,
    img: "/assets/plants/p3",
  },
  {
    id: 4,
    name: "Calathea",
    category: 4,
    price: 40,
    lightNeeds: "Medium Light",
    waterNeeds: "High Water",
    tag: "BestSelling",
    ratings: 4.6,
    sell: 10,
    img: "/assets/plants/p4",
  },
  {
    id: 5,
    name: "Monstera Deliciosa",
    category: 1,
    price: 40,
    lightNeeds: "Medium Light",
    waterNeeds: "High Water",
    tag: "BestSelling",
    ratings: 4.6,
    sell: 55,
    img: "/assets/plants/p5",
  },
  {
    id: 6,
    name: "Aloe Vera",
    category: 3,
    price: 20,
    lightNeeds: "Full Sun",
    waterNeeds: "Low Water",
    tag: "NewArrival",
    ratings: 4.5,
    sell: 95,
    img: "/assets/plants/p6",
  },
  {
    id: 7,
    name: "Snake Plant",
    category: 1,
    price: 35,
    lightNeeds: "Low Light",
    waterNeeds: "Low Water",
    tag: "BestSelling",
    ratings: 4.9,
    sell: 150,
    img: "/assets/plants/p7",
  },
  {
    id: 8,
    name: "Peace Lily",
    category: 4,
    price: 28,
    lightNeeds: "Low Light",
    waterNeeds: "Moderate Water",
    tag: "BestSelling",
    ratings: 4.8,
    sell: 70,
    img: "/assets/plants/p8",
  },
  {
    id: 9,
    name: "Bonsai",
    category: 2,
    price: 60,
    lightNeeds: "Bright Light",
    waterNeeds: "Moderate Water",
    tag: "Premium",
    ratings: 4.7,
    sell: 25,
    img: "/assets/plants/p9",
  },
  {
    id: 10,
    name: "Cactus",
    category: 3,
    price: 15,
    lightNeeds: "Full Sun",
    waterNeeds: "Low Water",
    tag: "BestSelling",
    ratings: 4.6,
    sell: 110,
    img: "/assets/plants/p10",
  },
  {
    id: 11,
    name: "ZZ Plant",
    category: 1,
    price: 32,
    lightNeeds: "Any",
    waterNeeds: "Low Water",
    tag: "NewArrival",
    ratings: 4.8,
    sell: 65,
    img: "/assets/plants/p11",
  },
  {
    id: 12,
    name: "Rubber Plant",
    category: 2,
    price: 38,
    lightNeeds: "Medium Light",
    waterNeeds: "Moderate Water",
    tag: "BestSelling",
    ratings: 4.7,
    sell: 40,
    img: "/assets/plants/p12",
  },
  {
    id: 13,
    name: "Lavender",
    category: 4,
    price: 22,
    lightNeeds: "Full Sun",
    waterNeeds: "Any",
    tag: "Seasonal",
    ratings: 4.5,
    sell: 90,
    img: "/assets/plants/p13",
  },
  {
    id: 14,
    name: "Orchid",
    category: 4,
    price: 50,
    lightNeeds: "Bright Light",
    waterNeeds: "High Water",
    tag: "Premium",
    ratings: 4.9,
    sell: 33,
    img: "/assets/plants/p14",
  },
  {
    id: 15,
    name: "Spider Plant",
    category: 1,
    price: 18,
    lightNeeds: "Medium Light",
    waterNeeds: "Any",
    tag: "BestSelling",
    ratings: 4.6,
    sell: 77,
    img: "/assets/plants/p15",
  },
  {
    id: 16,
    name: "Jade Plant",
    category: 3,
    price: 27,
    lightNeeds: "Bright Light",
    waterNeeds: "Low Water",
    tag: "BestSelling",
    ratings: 4.8,
    sell: 58,
    img: "/assets/plants/p16",
  },
];
